server:
  port: 9000
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mxsm/spring-config.git
          search-paths: config-repo,config-repo/config-repo1
#          uri: file://D:/github/spring-config
#          search-paths: config-repo,config-repo/config-repo1



            