server:
  port: 9000

management:
  security:
    enabled: false

---

#spring: 
#  profiles:
#    active: dev

---

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mxsm/config-repo.git
          search-paths: ./,config-repo/config-repo1
#          uri: file://D:/github/spring-config
#          search-paths: config-repo,config-repo/config-repo1



            