server:
  port: 9000
  
spring:
  cloud:
    config:
      server:
        git:
          uri: file://D:/github/spring-config
          search-paths: config-repo,config-repo/config-repo1



            